parameters:
  sonar_token: ''

jobs:
- job: Sonar_SAST_Scan_Job
  container: maven:3.8.1-openjdk-17-slim
  steps:
  - script: |
      mvn verify package sonar:sonar -Dsonar.host.url="https://sonarcloud.io/" -Dsonar.organization=tech365sec1 -Dsonar.projectKey=tech365sec1 -Dsonar.token=$(sonar_token)
    displayName: "Integrate SAST using SonarCloud to populate code coverage and secure pipeline variable in Azure DevOps DevSecOps Pipeline"